### ISSUE TITLE
question about the package

### ISSUE THREAD

**Issue by 12rambau** [missinglinkelectronics/sphinxcontrib-globalsubs#2]
What is the difference between using this package and setting a `rst_prolog` in my conf.py file ? 

https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-rst_prolog

**Comment by sephalon** [comment]
Thank you for the hint, as I am not using Sphinx on a regular basis anymore I was not aware of this new feature introduced in Sphinx 1.0. In fact it is my understanding that `rst_prolog` does provide a complete upstream replacement for this extension. We will consider obsoleting sphinxcontrib-globalsubs in favor of `rst_prolog`.
